services:
  redis:
    image: redis:7-alpine
    container_name: redis-tutorial
    ports:
      - "6379:6379"

    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis-tutorial-data:/data

  mongo:
    image: mongo:7
    container_name: redis-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ DATABASE: redis_tutorial_db
    volumes:
      - redis-tutorial-mongo-data:/data/db

volumes:
  redis-tutorial-data:
  redis-tutorial-mongo-data:

